services:
  ch-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "18123:8123"   # HTTP
      - "19000:9000"   # Native TCP
    environment:
      CLICKHOUSE_DB: my_database
      CLICKHOUSE_USER: VictorJuiz
      CLICKHOUSE_PASSWORD: 1865
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./volumes/clickhouse/data:/var/lib/clickhouse/:Z,U
      - ./volumes/clickhouse/logs:/var/log/clickhouse-server/:Z,U
    networks:
      - ethereum-etl-net
    init: true

  ch-ui:
    image: caioricciuti/ch-ui:latest
    container_name: clickhouse-ui
    restart: always
    ports:
      - "5521:5521"
    depends_on:
      - ch-server
    environment:
      VITE_CLICKHOUSE_URL: "http://localhost:18123"
      VITE_CLICKHOUSE_USER: "VictorJuiz"
      VITE_CLICKHOUSE_PASS: "1865"
      VITE_CLICKHOUSE_REQUEST_TIMEOUT: "30000"
    networks:
      - ethereum-etl-net

  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222" # for jetstream
      - "8222:8222"
    command:
      - -c
      - /etc/nats/nats.conf
      - "--server_name=nats-server"
      - "--cluster_name=NATS"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    volumes:
      - ./volumes/nats:/data:Z
      - ./nats.conf:/etc/nats/nats.conf:ro
    networks:
      - ethereum-etl-net
  
  memgraph-mage:
    image: memgraph/memgraph-mage
    container_name: memgraph-mage
    init: true
    ports:
      - "7687:7687"
      - "7444:7444"
    volumes:
      - ./volumes/memgraph/var/lib:/var/lib/memgraph:Z,U
      - ./volumes/memgraph/var/log:/var/log/memgraph:Z,U
    networks:
      - ethereum-etl-net
  lab:
    image: memgraph/lab
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    environment:
      QUICK_CONNECT_MG_HOST: memgraph-mage
    networks:
      - ethereum-etl-net

networks:
  ethereum-etl-net:
    name: ethereum-etl-net
    driver: bridge
