x-defaults: &defaults
  init: true
  restart: unless-stopped

services:
  clickhouse:
    <<: *defaults
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse

  redis:
    <<: *defaults
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
